# Generated by Django 4.1.7 on 2023-06-23 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_royal_family'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Royal_Family',
        ),
    ]
