# Generated by Django 4.1.7 on 2023-06-23 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_delete_royal_family'),
    ]

    operations = [
        migrations.CreateModel(
            name='Royal_Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('summary', models.TextField()),
                ('photo', models.ImageField(blank=True, upload_to='photos/%y/%m/%d/')),
            ],
        ),
    ]
