# Generated by Django 4.1.7 on 2023-06-28 09:22

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_page_delete_royal_family'),
    ]

    operations = [
        migrations.CreateModel(
            name='Popurlar_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('content', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(blank=True, upload_to='page/%y/%m/%d/')),
            ],
        ),
    ]
