# Generated by Django 4.1.7 on 2023-06-28 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_popurlar_page'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Popurlar_page',
            new_name='Popular_page',
        ),
    ]
