# Generated by Django 4.1.7 on 2023-06-28 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_rename_popurlar_page_popular_page'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Popular_page',
            new_name='Popular',
        ),
    ]
