# Generated by Django 4.1.7 on 2023-06-28 10:50

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_rename_popular_page_popular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='family',
            name='summary',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
